apiVersion: apps/v1
kind: Deployment
metadata:
  name: crate-webapp
spec:
  replicas: 1
  template:
    spec: # Pod spec
      containers:
      - name: webapp
        image: "ronaksuchak/webapp:latest"
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: crate-config-map
        resources:
          requests:
            memory: "16Mi" 
            cpu: "50m"    # 500milliCPUs (1/2 CPU)
          limits:
            memory: "128Mi"
            cpu: "100m"